[VoronoiMeshes]
git-tree-sha1 = "f3dfac9a10d959bd4f277c19e36fb7e56a8bde83"
lazy = true
[[VoronoiMeshes.download]]
url = "https://github.com/ClimFlows/ClimFlowsData/raw/data/VoronoiMeshes.tar.gz"
sha256 = "870776a4389161ad6882fde2ec7223f840e968fb1156d40bed7d8aa318bb3562"


