[VoronoiMeshes]
git-tree-sha1 = "1ed305fba4bad73ec2ed55ada8a1a0e07c389bf2"
lazy = true
[[VoronoiMeshes.download]]
url = "https://github.com/ClimFlows/ClimFlowsData/raw/data/VoronoiMeshes.tar.gz"
sha256 = "21d2e5ebd06da44ed7386f65929cedc43d8cd72ee5d1256c32f39003182d68e0"

