name = "ClimFlowsData"
uuid = "f57ce217-a21f-4063-8e40-561e9bf56723"
authors = ["Thomas Dubos <thomas.dubos@lmd.ipsl.fr>"]
version = "0.1.3"

[deps]
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
